openapi: 3.0.1
info:
  title: Appointments API
  description: API for managing appointments
  version: v1
paths:
  /api/Appointments:
    get:
      tags:
        - Appointments
      parameters:
        - name: date
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
    post:
      tags:
        - Appointments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          text/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Success
  '/api/Appointments/{id}':
    delete:
      tags:
        - Appointments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    Appointment:
      required:
        - description
        - endTime
        - startTime
        - title
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          maxLength: 100
          minLength: 0
          type: string
        description:
          maxLength: 500
          minLength: 0
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
      additionalProperties: false